before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: GwllIyOpshigNS6SlEfATe3mckBVoKh/+riKx9uRf3SC0da3TpjetgRfFy1VUVqPM68jCSG380LHcalcqlO9uVH+tXsoh3gVdDMOr2EZ9RYJYpA1rgwnfmuPXXdQSmmWjkOG5WCL57x2n5e75cjh1Eljlwh+P/c2zQS3jywC4o8l7fNrl7/Mqwf6Gj3EpBFADZ0eNyPAhyIbr4n+hxaJYm8tUX+FLc6JpnQJbBWUWeo8ORAioLs8NI0pK4HVQsq+39O2Ehvsrrskh45pBqMqfo0wL6rZAE6Vz2pKu0uclfsZZe0nYY9GjI26et1s1wjCh9BQNluc/zwW8JKnHnOdsP95vCrsm1aeTkqWNAKmKL1JgX9m8IJEXoQZryawNu+9TUAduB/gnPS6vEAZxSzcdw5DgtXb9CN6wKuuFlxn9a1VOQL2t39WMK7HWFH4FhG6EPuBzvIdK1TLupXneaeFaK2s3iJYenb1qXdJXn7zUUUSBVYB56a7vNdiLyHHUUp8O8LShgVVQUpk/CKm1w2rR8OdBOv2OY+hiotOoaoh+N4YIsgE+GcXOpNx08fQK90t7y7p0nxyAUaWv/aNnMHano++Bnof4MVEy+8xaIZln18oeP8UgODLdm3neV4AWGFlZ1ikEa8CsFOzfXqnXKp9TcWFn6Jy0k9reEVlqieJZRU= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
